version: "3.8"
services:
    dockerjupytercontainer:
        image: "dockerjupyter:1.0"
        ports:
          - 8765:8765
        volumes:
            - ${MYFOLDER}/PythonFundamentalsLiveLessons:/opt/service/PythonFundamentalsLiveLessons
            - ${MYFOLDER}/PythonLive:/opt/service/PythonLive
        command:
          - "jupyter-lab"
          - "--ip=0.0.0.0"
          - "--no-browser"
          - "--allow-root"
          - "--port=8765"
          - "--NotebookApp.password=''"
          - "--NotebookApp.token=''"  